// <auto-generated />
using System;
using EfCompositeQueryBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCompositeQueryBug.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfCompositeQueryBug.Entities.EntityBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GuidProperty")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("ParentId");

                    b.ToTable("BaseEntities");

                    b.HasDiscriminator<string>("EntityType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EfCompositeQueryBug.Entities.EntityA", b =>
                {
                    b.HasBaseType("EfCompositeQueryBug.Entities.EntityBase");

                    b.HasDiscriminator().HasValue("A");
                });

            modelBuilder.Entity("EfCompositeQueryBug.Entities.EntityB", b =>
                {
                    b.HasBaseType("EfCompositeQueryBug.Entities.EntityBase");

                    b.Property<long>("LongProperty")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("B");
                });

            modelBuilder.Entity("EfCompositeQueryBug.Entities.EntityC", b =>
                {
                    b.HasBaseType("EfCompositeQueryBug.Entities.EntityB");

                    b.HasDiscriminator().HasValue("C");
                });

            modelBuilder.Entity("EfCompositeQueryBug.Entities.EntityBase", b =>
                {
                    b.HasOne("EfCompositeQueryBug.Entities.EntityA", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EfCompositeQueryBug.Entities.EntityC", b =>
                {
                    b.OwnsOne("EfCompositeQueryBug.Entities.NestedEntity", "NestedProperty", b1 =>
                        {
                            b1.Property<Guid>("EntityCId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("PropertyA")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("PropertyB")
                                .HasColumnType("bigint");

                            b1.HasKey("EntityCId");

                            b1.ToTable("BaseEntities");

                            b1.ToJson("NestedProperty");

                            b1.WithOwner()
                                .HasForeignKey("EntityCId");
                        });

                    b.Navigation("NestedProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
